apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchLabels:
            app: {{ .Release.Name }}
        topologyKey: kubernetes.io/hostname
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: api
        image: {{ .Values.werf.image.api }}
        command:
          - uvicorn 
          - main:express_bot
          - --host
          - "0.0.0.0"
          - --port
          - "8000"
          - --reload
        ports:
          - containerPort: 8000
        env:
          - name: ELASTIC_APM_ENVIRONMENT
            value: {{ .Values.env_name }}
          - name: EXPRESS_BOT_ID
            value: {{ .Values.express_botid }}
          - name: EXPRESS_BOT_KEY
            value: {{ .Values.express_botkey }}
          - name: OPENAI_URL
            value: {{ .Values.api_url }}
          - name: OPENAI_API_KEY
            value: {{ .Values.api_key }}
        readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 60
            timeoutSeconds: 5
        livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 120
            timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 64Mi