apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.env_url }}
    secretName: wildcard-tls
  rules:
  - host: {{ .Values.env_url }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 8000